
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Wed Jun 05 2024 16:07:11 GMT+0500 (Pakistan Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Eventinformation extends ContentItem {
    public pageTitle!: Elements.TextElement;
    public heading!: Elements.TextElement;
    public subHeading!: Elements.TextElement;
    public content!: Elements.RichTextElement;
    public image!: Elements.AssetsElement;
    public date!: Elements.TextElement;
    public time!: Elements.TextElement;
    public admissionPolicyImage!: Elements.AssetsElement;
    public admissionPolicyContent!: Elements.RichTextElement;
    public admissionPolicyNote!: Elements.TextElement;
    public metaTitle!: Elements.TextElement;
    public metaDescription!: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'page_title') {
                    return 'pageTitle';
                }
                if (elementName === 'sub_heading') {
                    return 'subHeading';
                }
                if (elementName === 'admission_policy_image') {
                    return 'admissionPolicyImage';
                }
                if (elementName === 'admission_policy_content') {
                    return 'admissionPolicyContent';
                }
                if (elementName === 'admission_policy_note') {
                    return 'admissionPolicyNote';
                }
                if (elementName === 'meta_title') {
                    return 'metaTitle';
                }
                if (elementName === 'meta_description') {
                    return 'metaDescription';
                }
                return elementName;
            })
        });
    }
}
