
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Wed Jun 05 2024 13:44:50 GMT+0500 (Pakistan Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Footer extends ContentItem {
    public logo!: Elements.AssetsElement;
    public content!: Elements.TextElement;
    public address!: Elements.TextElement;
    public phone!: Elements.TextElement;
    public email!: Elements.TextElement;
    public map!: Elements.AssetsElement;
    public copyright!: Elements.TextElement;
}
