
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Wed Jun 05 2024 16:37:36 GMT+0500 (Pakistan Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Galleryyears extends ContentItem {
    public year!: Elements.TextElement;
    public items!: Elements.LinkedItemsElement<ContentItem>;
}
