
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Wed Jun 05 2024 14:54:00 GMT+0500 (Pakistan Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Homepage extends ContentItem {
    public tabs!: Elements.LinkedItemsElement<ContentItem>;
    public stats!: Elements.LinkedItemsElement<ContentItem>;
    public aboutHeading!: Elements.TextElement;
    public aboutContent!: Elements.RichTextElement;
    public aboutBtnName!: Elements.TextElement;
    public aboutBtnLink!: Elements.TextElement;
    public aboutImage!: Elements.AssetsElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'about_heading') {
                    return 'aboutHeading';
                }
                if (elementName === 'about_content') {
                    return 'aboutContent';
                }
                if (elementName === 'about_btn_name') {
                    return 'aboutBtnName';
                }
                if (elementName === 'about_btn_link') {
                    return 'aboutBtnLink';
                }
                if (elementName === 'about_image') {
                    return 'aboutImage';
                }
                return elementName;
            })
        });
    }
}
