
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Wed Jun 05 2024 13:44:50 GMT+0500 (Pakistan Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Menu extends ContentItem {
    public date!: Elements.TextElement;
    public venue!: Elements.TextElement;
    public logo!: Elements.AssetsElement;
    public items!: Elements.LinkedItemsElement<ContentItem>;
}
