
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Wed Aug 23 2023 18:23:13 GMT+0500 (Pakistan Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class PartnerPage extends ContentItem {
    public pagetitle!: Elements.TextElement;
    public heading!: Elements.TextElement;
    public subHeading!: Elements.TextElement;
    public items!: Elements.LinkedItemsElement<ContentItem>;
    public metatitle!: Elements.TextElement;
    public metadescription!: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'sub_heading') {
                    return 'subHeading';
                }
                return elementName;
            })
        });
    }
}
